// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oybgrludxelubnwnwmtu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im95YmdybHVkeGVsdWJud253bXR1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc5MzAxODQsImV4cCI6MjA3MzUwNjE4NH0.AZH2JOgLTwx8UFKzRwCF9SXi4sxXn21re0ZOWuj2Eis";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});